import '../helpers/app_config.dart' as config;
import 'package:flutter/material.dart';
import 'font_family.dart';

final ThemeData themeData = new ThemeData(
  visualDensity: VisualDensity.adaptivePlatformDensity,
  fontFamily: AppFontFamily.mainFonts,
  primaryColor: Colors.white,
  floatingActionButtonTheme: FloatingActionButtonThemeData(
      elevation: 0, foregroundColor: Colors.white),
  brightness: Brightness.light,
  accentColor: config.Colors().mainColor(1),
  dividerColor: config.Colors().accentColor(0.1),
  focusColor: config.Colors().accentColor(1),
  hintColor: config.Colors().accentColor(1),
  textTheme: TextTheme(
    headline5: TextStyle(
        fontSize: 20.0,
        color: config.Colors().headlineTextColor(1),
        height: 1.35),
    headline4: TextStyle(
        fontSize: 18.0,
        fontWeight: FontWeight.w600,
        color: config.Colors().headlineTextColor(1),
        height: 1.35),
    headline3: TextStyle(
        fontSize: 20.0,
        fontWeight: FontWeight.w600,
        color: config.Colors().headlineTextColor(1),
        height: 1.35),
    headline2: TextStyle(
        fontSize: 22.0,
        fontWeight: FontWeight.w700,
        color: config.Colors().headlineTextColor(1),
        height: 1.35),
    headline1: TextStyle(
        fontSize: 22.0,
        fontWeight: FontWeight.w300,
        color: config.Colors().headlineTextColor(1),
        height: 1.5),
    subtitle1: TextStyle(
        fontSize: 15.0,
        fontWeight: FontWeight.w500,
        color: config.Colors().titleTextColor(1),
        height: 1.35),
    subtitle2: TextStyle(
        fontSize: 15.0,
        fontWeight: FontWeight.w500,
        color: config.Colors().titleTextColor(1),
        height: 1.35),
    headline6: TextStyle(
        fontSize: 16.0,
        fontWeight: FontWeight.w600,
        color: config.Colors().headlineTextColor(1),
        height: 1.35),
    bodyText2: TextStyle(
        fontSize: 12.0,
        color: config.Colors().subtitleTextColor(1),
        height: 1.35),
    bodyText1: TextStyle(
        fontSize: 14.0,
        color: config.Colors().subtitleTextColor(1),
        height: 1.35),
    caption: TextStyle(
        fontSize: 12.0,
        color: config.Colors().subtitleTextColor(1),
        height: 1.35),
  ),
);

final ThemeData themeDataDark =ThemeData(
  visualDensity: VisualDensity.adaptivePlatformDensity,
  fontFamily: AppFontFamily.mainFonts,
  primaryColor: Color(0xFF252525),
  brightness: Brightness.dark,
  scaffoldBackgroundColor: Color(0xFF2C2C2C),
  accentColor: config.Colors().mainDarkColor(1),
  dividerColor: config.Colors().accentDarkColor(0.1),
  hintColor: config.Colors().accentDarkColor(1),
  focusColor: config.Colors().accentDarkColor(1),
  textTheme: TextTheme(
    headline5: TextStyle(
        fontSize: 20.0,
        color: config.Colors().headlineTextDarkColor(1),
        height: 1.35),
    headline4: TextStyle(
        fontSize: 18.0,
        fontWeight: FontWeight.w600,
        color: config.Colors().headlineTextDarkColor(1),
        height: 1.35),
    headline3: TextStyle(
        fontSize: 20.0,
        fontWeight: FontWeight.w600,
        color: config.Colors().headlineTextDarkColor(1),
        height: 1.35),
    headline2: TextStyle(
        fontSize: 22.0,
        fontWeight: FontWeight.w700,
        color: config.Colors().headlineTextDarkColor(1),
        height: 1.35),
    headline1: TextStyle(
        fontSize: 22.0,
        fontWeight: FontWeight.w300,
        color: config.Colors().headlineTextDarkColor(1),
        height: 1.5),
    subtitle1: TextStyle(
        fontSize: 15.0,
        fontWeight: FontWeight.w500,
        color: config.Colors().titleTextDarkColor(1),
        height: 1.35),
    subtitle2: TextStyle(
        fontSize: 15.0,
        fontWeight: FontWeight.w500,
        color: config.Colors().subtitleTextDarkColor(1),
        height: 1.35),
    headline6: TextStyle(
        fontSize: 16.0,
        fontWeight: FontWeight.w600,
        color: config.Colors().headlineTextDarkColor(1),
        height: 1.35),
    bodyText2: TextStyle(
        fontSize: 12.0,
        color: config.Colors().subtitleTextDarkColor(1),
        height: 1.35),
    bodyText1: TextStyle(
        fontSize: 14.0,
        color: config.Colors().subtitleTextDarkColor(1),
        height: 1.35),
    caption: TextStyle(
        fontSize: 12.0,
        color: config.Colors().subtitleTextDarkColor(0.6),
        height: 1.35),
  ),
);
